#!/bin/zsh
# ugsetup <problem-source> <problem-code> <problem-name> <file-name>

# echo $1
# echo $2
# echo $3
# echo $4

mkdir $1$2"-"$3
cd $1$2"-"$3
touch $4.cpp
touch $4.in
touch $4.out
CPPCODE="#include <bits/stdc++.h>
using namespace std;
int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    // freopen(\"$4.in\", \"r\", stdin);
    // freopen(\"$4.out\", \"w\", stdout);
}"
echo "$CPPCODE" >> $4.cpp